name: 'Create/Update K8S Resources'

on: 
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_DBNAME: ${{ vars.POSTGRES_DBNAME }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  apply:
    name: 'Apply K8S Resources'
    runs-on: ubuntu-latest
    environment: production 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Update kubeconfig for EKS cluster
        run: aws eks --region us-east-1 update-kubeconfig --name $EKS_CLUSTER_NAME

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Apply Kubernetes manifest
        run: |
          kubectl apply -f k8s/db-secret.yaml
          kubectl apply -f k8s/api-service.yaml
          kubectl apply -f k8s/api-deployment.yaml